//layout.js
import localFont from "next/font/local";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const minecraftFont = localFont({
  src: [
    {
      path: "../fonts/MinecraftBold-nMK1.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-minecraft",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${minecraftFont.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
